wtf:
  refreshInterval: 1
  bamboohr:
    enabled: false
    position:
      top: 0
      left: 0
      height: 2
      width: 1
    refreshInterval: 900
    url: "https://api.bamboohr.com/api/gateway.php"
  gcal:
    currentIcon: "💥"
    enabled: false
    eventCount: 10
    position:
      top: 2
      left: 1
      height: 4
      width: 1
    refreshInterval: 300
    secretFile: "~/.wtf/gcal/client_secret.json"
  git:
    commitCount: 5
    enabled: true
    position:
      top: 0
      left: 2
      height: 2
      width: 3
    refreshInterval: 8
    repository: "/Users/chris/go/src/github.com/senorprogrammer/wtf"
  github:
    enabled: false
    organization: "BetterOfficeApps"
    position:
      top: 2
      left: 2
      height: 2
      width: 3
    refreshInterval: 300
    repo: "core-api"
    username: "senorprogrammer"
  jira:
    enabled: false
    position:
      top: 1
      left: 1
      height: 1
      width: 1
    refreshInterval: 900
  newrelic:
    applicationId: 10549735
    enabled: true
    deployCount: 7
    position:
      top: 4
      left: 2
      height: 1
      width: 3
    refreshInterval: 900
  opsgenie:
    enabled: false
    position:
      top: 2
      left: 0
      height: 2
      width: 1
    refreshInterval: 21600
  security:
    enabled: true
    position:
      top: 5
      left: 0
      height: 1
      width: 1
    refreshInterval: 3600
  status:
    enabled: true
    position:
      top: 5
      left: 2
      height: 3
      width: 3
    refreshInterval: 1
  weather:
    cityId: 6173331
    enabled: false
    language: "EN"
    position:
      top: 0
      left: 1
      height: 1
      width: 1
    tempUnit: "C"
    refreshInterval: 900
