wtf:
  grid:
    columns: [40]
    rows: [13, 3]
  refreshInterval: 1
  mods:
    security:
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    status:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
